# NumPy

### Basics

In [2]:
import numpy as np

In [3]:
# Initialization
arr = np.array([1,2,3,4])
matrix = np.array([[1,2],[3,4]])
print(np.array([1,2,3,4]))
print(np.array([[1,2],[3,4]]))
print(np.ones((2,2)))
print(np.zeros((2,2)))
print(np.diag([1,1]))

[1 2 3 4]
[[1 2]
 [3 4]]
[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]
[[1 0]
 [0 1]]


In [4]:
# Properties
print(type(arr), type(matrix))
print(arr.shape, matrix.shape)
print(arr.size, matrix.size)

<class 'numpy.ndarray'> <class 'numpy.ndarray'>
(4,) (2, 2)
4 4


In [5]:
# Ranges
print(np.arange(10))
print(np.arange(1,10,2))
print(np.arange(0,1,0.1))
print(np.linspace(1,10,5))
print(np.logspace(1,5,5))

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[ 1.    3.25  5.5   7.75 10.  ]
[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05]


In [6]:
# Random
print(np.random.rand(5)) # [0,1]
print(np.random.randn(5)) # Gaussian normal

[0.17132738 0.96778903 0.98162875 0.11282859 0.02558491]
[-2.6128264   2.54569455  0.13916563  0.0714964   1.19875483]


In [40]:
# Loading data from file
data = np.loadtxt("example.csv",skiprows=0,delimiter=" ")
data

array([[0.        , 3.5       , 1.7       , 1.30490198, 1.        ],
       [1.        , 7.4       , 3.6       , 2.12145178, 1.        ],
       [2.        , 1.2       , 3.8       , 2.73644   , 1.        ]])

In [41]:
# Save data to file
np.savetxt("example.csv",data)

In [81]:
# Access
print(matrix[0,0])
print(matrix[0])
print(matrix[0,:]) # [rowStart,rowEnd:colStart,colEnd]
print(matrix[:,0])

1
[1 2]
[1 2]
[1 3]


In [43]:
# Comprehension
compArr = np.array([i for i in np.linspace(1,10,4)])
compArr

array([ 1.,  4.,  7., 10.])

### Linear algebra

In [44]:
# Vectors
vec = np.array([1,2])
print(vec)
print(vec*2)
print(vec+2)
print(pow(vec,2))
print(vec.reshape(2,1))

[1 2]
[2 4]
[3 4]
[1 4]
[[1]
 [2]]


In [45]:
# Matrices
print(matrix)
print(matrix*2)
print(matrix+2)
print(matrix**2)
print(matrix*vec.reshape(2,1))

[[1 2]
 [3 4]]
[[2 4]
 [6 8]]
[[3 4]
 [5 6]]
[[ 1  4]
 [ 9 16]]
[[1 2]
 [6 8]]


In [46]:
# Dot product
colVec = vec.reshape(2,1)
print(np.dot(vec,vec))
print(np.dot(matrix,colVec))
print(np.dot(matrix,matrix))

5
[[ 5]
 [11]]
[[ 7 10]
 [15 22]]


In [47]:
# Matrix object
npMatrix = np.matrix(matrix)
print(npMatrix)
npVec = np.matrix(vec)
print(npVec)
npColVec = npVec.T
print(npColVec)

[[1 2]
 [3 4]]
[[1 2]]
[[1]
 [2]]


In [48]:
# Dot product
print(npVec*npColVec)
print(npMatrix*npColVec)
print(npMatrix*npMatrix)

[[5]]
[[ 5]
 [11]]
[[ 7 10]
 [15 22]]


In [49]:
# Other functions
print(np.inner(npVec,npVec)) # Inner product, uT*v
print(np.outer(npVec,npVec)) # Outer product, u*vT

[[5]]
[[1 2]
 [2 4]]


In [50]:
# Transformation
m = np.matrix([[1j,2j],[3j,4]])
print(m)
print(np.transpose(m)) # Transpose
print(np.conjugate(m)) # Conjugate
print(m.H) # Hermitian conjugate: T+C
print(np.real(m)) # Real
print(np.imag(m)) # Imaginary
print(np.abs(m)) # Absolute value

[[0.+1.j 0.+2.j]
 [0.+3.j 4.+0.j]]
[[0.+1.j 0.+3.j]
 [0.+2.j 4.+0.j]]
[[0.-1.j 0.-2.j]
 [0.-3.j 4.-0.j]]
[[0.-1.j 0.-3.j]
 [0.-2.j 4.-0.j]]
[[0. 0.]
 [0. 4.]]
[[1. 2.]
 [3. 0.]]
[[1. 2.]
 [3. 4.]]


In [51]:
# Computations
print(np.linalg.inv(m)) # Inverse
print(np.linalg.det(m)) # Determinant

[[ 0.46153846-0.30769231j -0.15384615-0.23076923j]
 [-0.23076923-0.34615385j  0.07692308+0.11538462j]]
(6.000000000000001+3.9999999999999996j)


### Data processing

In [73]:
# Basics
print(data)
print(np.shape(data)) # Shape
print(np.mean(data[0]),) # Mean of data
print(np.std(data[0])) # Standard dev
print(np.var(data[0])) # Variance
print(data[0].min()) # Min
print(data[0].max()) # Max
print(sum(data[0])) # Sum
print(np.prod(data[0])) # Product of elements
print(np.cumsum(data[0])) # Cumulative sum
print(np.cumprod(data[1])) # Cumulative product
print(np.diag(data).sum()) # Trace

[[0.         3.5        1.7        1.30490198 1.        ]
 [1.         7.4        3.6        2.12145178 1.        ]
 [2.         1.2        3.8        2.73644    1.        ]]
(3, 5)
1.5009803959999999
1.1470011710130321
1.3156116863052671
0.0
3.5
7.50490198
0.0
[0.         3.5        5.2        6.50490198 7.50490198]
[ 1.          7.4        26.64       56.51547542 56.51547542]
11.2


In [75]:
# Higher-dimensional arrays
m = np.random.rand(3,3)
print(m.max()) # Global max
print(m.max(axis=0)) # Max in each column
print(m.max(axis=1)) # Max in each row

0.9866187647021727
[0.78306921 0.71681885 0.98661876]
[0.83959847 0.76428941 0.98661876]


### Manipulating arrays

In [85]:
m = np.array([[ 0, 1, 2, 3, 4],
            [10, 11, 12, 13, 14],
            [20, 21, 22, 23, 24],
            [30, 31, 32, 33, 34]])
print(m.shape)
print(m.reshape((5,4)))
print(m.flatten())

(4, 5)
[[ 0  1  2  3]
 [ 4 10 11 12]
 [13 14 20 21]
 [22 23 24 30]
 [31 32 33 34]]
[ 0  1  2  3  4 10 11 12 13 14 20 21 22 23 24 30 31 32 33 34]


In [91]:
a = np.array([[1,2],[3,4]])
print(np.repeat(a,3))
print(np.tile(a,3))

[1 1 1 2 2 2 3 3 3 4 4 4]
[[1 2 1 2 1 2]
 [3 4 3 4 3 4]]


In [95]:
b = np.array([[5,6]])
print(np.concatenate((a,b),axis=0))
print(np.vstack((a,b)))
print(np.concatenate((a,b.T),axis=1))
print(np.hstack((a,b.T)))

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]
[[1 2 5]
 [3 4 6]]


In [104]:
b = a # Shallow copy
c = np.copy(a) # Deep copy
b[0,0] = 2
print(a)
print(c)

[[2 2]
 [3 4]]
[[1 2]
 [3 4]]


---

# SciPy